# Generated by Django 3.0 on 2020-02-07 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 2, 37, 17, 271632, tzinfo=utc), verbose_name='date published'),
        ),
    ]
