# Generated by Django 3.0 on 2020-04-13 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200207_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 1, 47, 42, 775685, tzinfo=utc), verbose_name='date published'),
        ),
    ]
